//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Extradition
    {
        public int Id { get; set; }
        public int IdEquipment { get; set; }
        public int Quantity { get; set; }
        public int IdStorages { get; set; }
        public int IdPersonnel { get; set; }
        public int IdUsers { get; set; }
        public string Date { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Personnel Personnel { get; set; }
        public virtual Users Users { get; set; }
        public virtual Storages Storages { get; set; }
    }
}
